reader:
  loading_strategy: dataset
  data_type: transaction
  reading_method: local
  local_path: /mnt/splinter-data/potito/datasets/netflix-prize-100m/ratings_processed.csv
  rating_type: explicit
  sep: ','
  labels:
    user_id_label: user_id
    item_id_label: item_id
    rating_label: rating
    timestamp_label: timestamp
writer:
  dataset_name: Netflix100M-NeuMF-Serial
  writing_method: local
  local_experiment_path: /mnt/splinter-data/potito/experiments/warprec-benchmark-2026/
splitter:
  test_splitting:
    strategy: random_holdout
    ratio: 0.1
dashboard:
  wandb:
    enabled: False
    team: your_wandb_team_here
    project: warprec-benchmark-2026
    group: Netflix100M-Serial
    api_key: your_wandb_api_key_here
    upload_checkpoints: False
  codecarbon:
    enabled: True
    save_to_file: True
    tracking_mode: process
    output_dir: /mnt/splinter-data/potito/experiments/warprec-benchmark-2026/Netflix100M-NeuMF-Serial/codecarbon/
models:
  NeuMF:
    optimization:
      block_size: 3000
    meta:
      save_model: True
    mf_embedding_size: [64, 128, 256]
    mlp_embedding_size: 64
    mlp_hidden_size: [[64, 32]]
    mf_train: True
    mlp_train: True
    dropout: 0.1
    reg_weight: 0.001
    weight_decay: 0.0001
    batch_size: 8192
    epochs: 2
    learning_rate: 0.001
    neg_samples: [0, 1]
evaluation:
  top_k: [10]
  metrics: [nDCG, Precision, Recall, HitRate, MAP]
  validation_metric: nDCG@10
  strategy: full
general:
  device: cuda
